version: '3.4'

#NETWORK
networks:
  springboot-app-network:
    driver: bridge

#SERVICES
services:
  # Backend
  java-springboot:
    container_name: JavaAPI
    build:
      dockerfile: Dockerfile
      context: ./server/springboot
    ports:
      - "8080:8080"
    volumes:
      - ./server/springboot:/app
    networks:
      - springboot-app-network
