version: '3.4'

#SERVICES
services:
  # Backend
  java-springboot:
    container_name: JavaAPI
    build: 
      dockerfile: Dockerfile
      context: ./backendsystem/
    ports:
      -  "8080:8080"
    volumes:
      - ./backendsystem:/app